name: rebuild node
on: 
  push:
    branches:
      - deploy

jobs:

  build:
    name: Build
    runs-on: self-hosted

    steps:     
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Cache npm packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-repo-${{ hashFiles('**') }}
          restore-keys: |
            ${{ runner.os }}-repo-
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16'
      - name: Install
        run: npm install -g yarn pm2              
      - name: Install backend        
        run: cd backend && yarn
      - name: Install frontend        
        run: cd frontend && yarn
      # - uses: actions/checkout@v3
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: 'npm'
      # - run: npm install -g yarn
      # - run: yarn setup
      - run: cp /home/web/sites/diramazioni/backend/.env backend/
      - run: cp /home/web/sites/diramazioni/frontend/.env frontend/
      - run: cp /home/web/sites/diramazioni/backend/ecosystem.config.js backend/
      - run: cp /home/web/sites/diramazioni/frontend/ecosystem.config.js frontend/
      - run: cd backend && NODE_ENV=production yarn build
      - run: cd backend && pm2 restart ecosystem.config.js
      - run: cd frontend && NODE_ENV=production yarn build
      - run: cd frontend && pm2 restart ecosystem.config.js
